# Generated by Django 3.2.9 on 2021-11-17 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
